name: 'Run Musicord'
on:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  run_musical_bot:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      GH_OAUTH_TOKEN: ${{ secrets.GH_OAUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Installing dependencies
        run: npm install

      - name: Run script
        run: npm run start
